# Live-Forensicator Config File
# https://github.com/Johnng007/Live-Forensicator
# ...

suspicious_executables:
  - block
  - go
  - take
  - 7zip.exe
  - \\nic.exe
  - '%compsec%'
  - '%comspec%'
  - wscript.exe
  - regsvr32.exe
  - mshta.exe
  - \\csc.exe
  - whoami.exe
  - \\pl.exe
  - \\nc.exe
  - nmap.exe
  - psexec.exe
  - psexesvc.exe
  - plink.exe
  - kali
  - mimikatz
  - procdump.exe
  - dcom.exe
  - Inveigh.exe
  - LockLess.exe
  - Logger.exe
  - PBind.exe
  - PS.exe
  - Rubeus.exe
  - RunasCs.exe
  - RunAs.exe
  - SafetyDump.exe
  - SafetyKatz.exe
  - Seatbelt.exe
  - SExec.exe
  - SharpApplocker.exe
  - SharpChrome.exe
  - SharpCOM.exe
  - SharpDPAPI.exe
  - SharpDump.exe
  - SharpEdge.exe
  - SharpEDRChecker.exe
  - SharPersist.exe
  - SharpHound.exe
  - SharpLogger.exe
  - SharpPrinter.exe
  - SharpRoast.exe
  - SharpSC.exe
  - SharpSniper.exe
  - SharpSocks.exe
  - SharpSSDP.exe
  - SharpTask.exe
  - SharpUp.exe
  - SharpView.exe
  - SharpWeb.exe
  - SharpWMI.exe
  - Shhmon.exe
  - SweetPotato.exe
  - Watson.exe
  - WExec.exe
  - 7zip.exe

suspicious_PS_commands:
  - FromBase64String
  - "Get-WMIObject"
  - "Get-VaultCredential"
  - "Get-ServicePerms"
  - "Get-UnattendedInstallFiles"
  - "Get-PassHashes"
  - "Get-KerberosPolicy"
  - "Get-KerberosPolicy"
  - "Invoke-Shellcode"
  - "Invoke-MimikatzWDigestDowngrade"
  - "Invoke-TokenManipulation"
  - "Invoke-DllEncode"
  - "Invoke-ServiceStart"
  - "Invoke-ServiceDisable"
  - "Invoke-AllChecks"
  - "Invoke-MassTemplate"
  - "Invoke-CredentialsPhish"
  - "Invoke-PowerShellUdp"
  - "Invoke-PowerShellTcp"
  - "Invoke-Encode"
  - "EncodedCommand"
  - "DownloadString"
  - "Out-CHM"
  - "DllInjection"
  - "System.Management"
  - "Execute-OnTime"
  - "Write-CMDServiceBinary"
  - "Write-ServiceEXECMD"
  - "Execute-DNSTXT-Code"
  - "Download_Execute"
  - "Run-EXEonRemote"
  - "StringtoBase64"
  - "Add-Persistence"
  - "Discover-PSMSSQLServers"
  - "Discover-PSInterestingServices"
  - "Discover-PSInterestingServices"
  - "PowershellEmpire"
  - "Invoke-Obfuscation-master"
  - "-EncodedCommand"
  - "New-Object"
  - "DownloadString"
  - "-ExecutionPolicy bypass"
  - "DomainPasswordSpray"
  - "Get-GPPPassword"
  - "Get-ServiceUnquoted"
  - "Get-RegAlwaysInstallElevated"
  - "Get-Webconfig"
  - "Get-LsaSecret"
  - "Get-PSADForestKRBTGTInfo"
  - "Invoke-Command"
  - "Invoke--Shellcode"
  - "Invoke-NinjaCopy"
  - "Invoke-CallbackIEX"
  - "Invoke-ServiceUserAdd"
  - "Invoke-ServiceStop"
  - "Invoke-FindDLLHijack"
  - "Invoke-MassCommand"
  - "Invoke-MassTokens"
  - "Invoke-BruteForce"
  - "Invoke-PsGcatAgent"
  - "Invoke-PoshRatHttp"
  - "Invoke-Decode"
  - "New-ElevatedPersistenceOption"
  - "DownloadFile"
  - "Out-HTA"
  - "ReflectivePEInjection"
  - "Restore-ServiceEXE"
  - "DNS_TXT_Pwnage"
  - "Write-UserAddMSI"
  - "Enable-DuplicateToken"
  - "Download-Execute-PS"
  - "Copy-VSS"
  - "Port-Scan"
  - "Do-Exfiltration"
  - "Remove-Persistence"
  - "Discover-PSMSExchangeServers"
  - "Discover-PSMSExchangeServers"
  - "Mimikatz"
  - "GetProcAddress"
  - "Out-EncodedWhitespaceCommand"
  - "-enc"
  - "Net.WebClient"
  - "Invoke-Expression"
  - "Execute-Command-MSSQL"
  - "PasswordSpray"
  - "Get-Keystrokes"
  - "Get-ServiceEXEPerms"
  - "Get-RegAutoLogon"
  - "Get-ApplicationHost"
  - "Get-Information"
  - "Get-PSADForestInfo"
  - "Invoke-Expression"
  - "Invoke-ShellcodeMSIL"
  - "Invoke-CredentialInjection"
  - "Invoke-PSInject"
  - "Invoke-ServiceCMD"
  - "Invoke-ServiceEnable"
  - "Invoke-FindPathHijack"
  - "Invoke-MassMimikatz"
  - "Invoke-ADSBackdoor"
  - "Invoke-PowerShellIcmp"
  - "Invoke-PoshRatHttps"
  - "Invoke-PowerShellWmi"
  - "Invoke-CreateCertificate"
  - "wsman"
  - "Out-Word"
  - "Out-Minidump"
  - "Base64"
  - "Add-ScrnSaveBackdoor"
  - "Write-UserAddServiceBinary"
  - "Write-ServiceEXE"
  - "Remove-Update"
  - "Execute-Command-MSSQL"
  - "Check-VM"
  - "Remove-PoshRat"
  - "Parse_Keys"
  - "Find-PSServiceAccounts"
  - "powercat"
  - "ICM"
  - "Out-Encoded"
  - "-w hidden"
  - "-windowstyle hidden"
  - "Net.WebClient"
  - Execute-DNSTXT-Code
  - "Password"
  - "Get-TimedScreenshot"
  - "Get-PSADForestInfo"
  - "iex"
  - "Invoke-MassSearch"
  - "Invoke-PSGcat"
  - "Invoke-NetworkRelay"
  - "Enter-PSSession"
  - "Out-Excel"
  - "HTTP-Backdoor"
  - "System.Reflection"
  - "Gupt-Backdoor"
  - "Create-MultipleSessions"
  - "TexttoEXE"
  - "Add-Exfiltration"
  - "powersploit"
  - ".invoke"
  - "[Convert]::FromBase64String"
  - "DownloadFile"
  - "-Exec bypass"
  - Execute-OnTime
  - "lsass"
  - "Out-Java"
  - "Find-AVSignature"
  - "Base64ToString"
  - " -e "
  - "iex("
  - ExetoText


# other sections and values can be defined here
# ...
